Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

// Dla pracy z html ("zmienia typ")
namespace Shop.Controllers
{
    public class BooksController : Controller
    {
        private readonly IAllBooks _allBooks;
        private readonly IAddBook _addBook;
        private readonly IBooksCategory _allCategories;

        public BooksController(IAllBooks iAllBooks, IAddBook iaddBook, IBooksCategory iBooksCategory)
        {
            _allBooks = iAllBooks;
            _addBook = iaddBook;
            _allCategories = iBooksCategory;
        }

        // Lista wszystkich książek
        // Lista książek według kategorii
        [Route("Books/List")]
        [Route("Books/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Book> books = null;
            string currCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                books = _allBooks.Books.OrderBy(i=>i.id);
            } else {
                if (string.Equals("biography", category, StringComparison.OrdinalIgnoreCase)) {
                    books = _allBooks.Books.Where(i => i.Category.categoryName.Equals("Biografie")).OrderBy(i => i.id);
                    currCategory = "Biografie";
                } 
                else if (string.Equals("forChildren", category, StringComparison.OrdinalIgnoreCase))
                {
                    books = _allBooks.Books.Where(i => i.Category.categoryName.Equals("Dla dzieci")).OrderBy(i => i.id);
                    currCategory = "Dla dzieci";
                } 
                else if (string.Equals("history", category, StringComparison.OrdinalIgnoreCase))
                {
                    books = _allBooks.Books.Where(i => i.Category.categoryName.Equals("Historia")).OrderBy(i => i.id);
                    currCategory = "Historia";
                } 
                else if (string.Equals("comics", category, StringComparison.OrdinalIgnoreCase))
                {
                    books = _allBooks.Books.Where(i => i.Category.categoryName.Equals("Komiks")).OrderBy(i => i.id);
                    currCategory = "Komiks";
                }
                else if (string.Equals("crimeSensationThriller", category, StringComparison.OrdinalIgnoreCase))
                {
                    books = _allBooks.Books.Where(i => i.Category.categoryName.Equals("Kryminał, sensacja, thriller")).OrderBy(i => i.id);
                    currCategory = "Kryminał, sensacja, thriller";
                }
                else if (string.Equals("kitchenDiet", category, StringComparison.OrdinalIgnoreCase))
                {
                    books = _allBooks.Books.Where(i => i.Category.categoryName.Equals("Kuchnia i diety")).OrderBy(i => i.id);
                    currCategory = "Kuchnia i diety";
                }
                else if (string.Equals("literatureTraditional", category, StringComparison.OrdinalIgnoreCase))
                {
                    books = _allBooks.Books.Where(i => i.Category.categoryName.Equals("Literatura obyczajowa")).OrderBy(i => i.id);
                    currCategory = "Literatura obyczajowa";
                }
                else if (string.Equals("literatureBeautifulForeign", category, StringComparison.OrdinalIgnoreCase))
                {
                    books = _allBooks.Books.Where(i => i.Category.categoryName.Equals("Literatura piękna obca")).OrderBy(i => i.id);
                    currCategory = "Literatura piękna obca";
                }
                else if (string.Equals("lliteratureBeautifulPoland", category, StringComparison.OrdinalIgnoreCase))
                {
                    books = _allBooks.Books.Where(i => i.Category.categoryName.Equals("Lliteratura piękna polska")).OrderBy(i => i.id);
                    currCategory = "Lliteratura piękna polska";
                }
            }
            
            var bookObj = new BooksListViewModel
            {
                allBooks = books,
                currCategory = currCategory
            };

            ViewBag.Title = "Book";

            return View(bookObj);
        }

        // Strona z wypwłnianiem danych o książce
        public IActionResult AddBook()
        {
            return View();
        }

        // Strona z wypwłnianiem danych o książce po kliknięciu przycisku
        [HttpPost]
        public IActionResult AddBook(Book book)
        {
            // poprawne wypełnienie inputs
            if (ModelState.IsValid)
            {
                // dodawanie książki do BD
                _addBook.createBook(book);
                return RedirectToAction("Complete");
            }
            return View(book);
        }

        public IActionResult Complete()
        {
            ViewBag.Message = "Książka dodana";
            return View();
        }
    }
}

Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Data.interfaces;
using Shop.Data.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class ShopCartController : Controller
    {
        private IAllBooks _bookRep;
        private readonly ShopCart _shopCart;
        public ShopCartController(IAllBooks bookRep, ShopCart shopCart)
        {
            _bookRep = bookRep;
            _shopCart = shopCart;
        }

        // dla html(szablon strony)
        public ViewResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.listShopItems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };

            return View(obj);
        }

        // dla html(przekierować na inną strone)
        public RedirectToActionResult addToCart(int id)
        {
            var item = _bookRep.Books.FirstOrDefault(i => i.id == id);
            if (item != null)
            {
                _shopCart.AddToCart(item);
            }
            return RedirectToAction("Index");
        }

    }
}

Views/Shared/AllBooks.cshtml
@model Shop.Data.Models.Book

<div class="login__body">
    <div class="img">
        <img src=@Model.img class="img_book">
    </div>
    <div class="data">
        <div class="title_book">
            <p>@Model.name</p>
        </div>
        <div class="data_book">
            <p>Autor: <span>@Model.author</span></p>
        </div>
        <div class="data_book">
            <p>Cena książki: <span>@Model.price.ToString("c")</span></p>
        </div>
        <div class="data_book">
            <p class="desc">Opis</p>
            <span>@Model.desc</span>
        </div>
        <div class="button_buy">
            <button><a asp-controller="ShopCart" asp-action="addToCart" asp-route-id="@Model.id">Kupić</a></button>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/Home.css" type="text/css" />
    <link rel="stylesheet" href="~/css/Navigation.css" type="text/css" />
    <link rel="stylesheet" href="~/css/Order.css" type="text/css" />
</head>
<body>
    <div class="top-stripe">
        <p><a class="personal_account" href="/Books/List">Strona Główna</a></p>
        <p id="pa" class="personal_account">Kategorie książek</p>
        <p><a class="personal_account" asp-controller="Books" asp-action="AddBook">Dodać książkę</a></p>
        <p><a class="personal_account" asp-controller="ShopCart" asp-action="Index">Koszyk</a></p>
        <h2>BookShop</h2>
    </div>
    <div class="top_stripe_pa button_pa" id="div_pa">
        <button><a href="/Books/List/biography">Biografie</a></button>
        <button><a href="/Books/List/forChildren">Dla dzieci</a></button>
        <button><a href="/Books/List/history">Historia</a></button>
        <button><a href="/Books/List/comics">Komiks</a></button>
        <button><a href="/Books/List/crimeSensationThriller">Kryminał, sensacja, thriller</a></button>
        <button><a href="/Books/List/kitchenDiet">Kuchnia i diety</a></button>
        <button><a href="/Books/List/literatureTraditional">Literatura obyczajowa</a></button>
        <button><a href="/Books/List/literatureBeautifulForeign">Literatura piękna obca</a></button>
        <button><a href="/Books/List/lliteratureBeautifulPoland">Lliteratura piękna polska</a></button>
    </div>
    <div>
        @RenderBody()
    </div>
    <script src="~/js/Menu.js"></script>
</body>
</html>